
# 数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.154.201:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

# zookeeper

curator:
  retryCount: 5    #重试次数
  elapsedTimeMs: 5000    #重试间隔时间
  connectString: 192.168.154.201:2181/test    # zookeeper 地址
  sessionTimeoutMs: 60000    # session超时时间
  connectionTimeoutMs: 5000    # 连接超时时间